### ISSUE TITLE
How to make tasks?

### ISSUE THREAD

**Issue by ZLOIRUSSKII** [dromse/obsidian-gamified-tasks#50]
Hi. I'm new into Obsidian so kinda confused. I read getting started guide. Still don't understand where do you even write #tags so it would work. Screenshot would be nice.

**Comment by ZLOIRUSSKII** [comment]
![image](https://github.com/dromse/obsidian-gamified-tasks/assets/175289565/00749739-2c9f-4f72-9370-9950ed1f4a65)
Figured it out. This how it shoud looks like so it would work. Other stuff explained better.

**Comment by dromse** [comment]
Okay, I added it to wiki
