### ISSUE TITLE
[Feature]: Possibility to change the formatting of the done date for completed tasks.

### ISSUE THREAD

**Issue by Victhors** [dromse/obsidian-gamified-tasks#54]
### What kind of feature do you want?

I want to be able to change the formatting of the completion date of the completed tasks to the formatting that the Task Plugin accepts, so that the dataviews of this larger plugin that I use together with gamified tasks would also work for the tasks completed by gamified.

Example: 
Gamified use that formating: ✅ [[2024-08-23|2024-08-23 | 12:11]]
Task Plugin use that formating: ✅ 2024-08-23

the formatting that the tasks gamified plugin uses is much better than the formatting of the task plugin, but as the task plugin is a more important plugin in my vault because of the daviews etc, I want to be able to change it. 

### Additional questions

- [X] I want to work on this feature request

**Comment by dromse** [comment]
Hi! I try to add a setting for it in future releases, thanks for suggestion!

**Comment by dromse** [comment]
4bc8397
