### ISSUE TITLE
[Feature]: add a new task to a daily note

### ISSUE THREAD

**Issue by dromse** [dromse/obsidian-gamified-tasks#65]
### What kind of feature do you want?

Add a new option to `save to daily note` to the new task creation modal.

### Additional questions

- [X] I want to work on this feature request

**Comment by kidclone3** [comment]
Hi @dromse , I want to ask if you can add support for different format of daily notes and make its configurable.
I am using this daily note format from a template and I want to use it with your plugin.

![Image](https://github.com/user-attachments/assets/50d67288-ff25-49b6-8f0c-0416d4c0daaa)
