### ISSUE TITLE
Receiving rewards without using the add-on's special panel.

### ISSUE THREAD

**Issue by bav2653** [dromse/obsidian-gamified-tasks#97]
### What kind of feature do you want?

Hello.

Can I simply open Obsidian and get a reward with the press of a single button after completing each task? I don't like that all operations are done through a special panel—it involves too many unnecessary steps.

https://github.com/user-attachments/assets/838c9165-12c6-4f10-ba21-af51d14426d3

### Additional questions

- [ ] I want to work on this feature request

**Comment by dromse** [comment]
Hi, @bav2653! For now, the plugin doesn't have this feature, but I'll try to incorporate this in future releases. Also, this is a duplication of issue #68 , so I close this issue if you don't mind 😄

**Comment by dmitryguskv** [comment]
Totally agree. Haven't you found some way to bypass this? Such a great plugin, but this makes it so less comfortable. Dromse, I'm begging you for this feature
